// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftxxtdawxypshxtxjtco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0eHh0ZGF3eHlwc2h4dHhqdGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4MDU4NjYsImV4cCI6MjA1NDM4MTg2Nn0.OrWioY2AFYJHG91RIdjbkGKec8pNmAYMjao_vUMNEMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);